#!/bin/bash
#cd /Users/kellman/docker/gitbook
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd $DIR

docker run --rm -h gitbook --name gitbook -v $PWD/doc:/doc -p 4000:4000 -it gitbook:latest


